---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raj-deployment
  namespace: webprod
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raj-dev
  template:
    metadata:
      labels:
        app: raj-dev
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name:  efs-storage
            mountPath:  /usr/share/nginx/html
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc