apiVersion: v1
kind: Service
metadata:
  name: raj-svc
  namespace: raj-ns
spec:
  type: NodePort
  selector:
    app: raj-dev
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
